---
- name: create a variables
  hosts: webservers
  tasks:
    - name: create directory
      ansible.builtin.file:
        path: "{{directory}}"
        state: directory

    - name: create files
      ansible.builtin.file:
        path: "{{file}}"
        state: touch

    - name: create content
      ansible.builtin.copy:
        content: "{{content}}"
        dest: "{{directory}}/{{file}}"
